### ISSUE TITLE
Improve the docs

### ISSUE THREAD

**Issue by niutech** [PeerServer/peer-server#1]
What is this project about? The first sentence in the docs is:

> PeerServer is a peer-to-peer client server using WebRTC, where your browser acts as a server for other browsers across WebRTC peer-to-peer data channels.

So is it a client or a server? Which server - a web server, WebRTC server, WebSocket server, P2P server? P2P is in contrast to client-server. So how does the communication flow look like? Please improve the docs.

**Comment by swestwood** [comment]
Closing, docs were updated a few months after. Let me know if anything is still unclear.
