### ISSUE TITLE
Add License?

### ISSUE THREAD

**Issue by omphalos** [PeerServer/peer-server#2]
Any thoughts on adding a permissive license (like MIT) to this project?

**Comment by bluabaleno** [comment]
Yeah that would be nice.

**Comment by onebree** [comment]
@swestwood Massive +1 on this idea. I am wary about looking into this project, if it has no license (let alone permissive).

**Comment by swestwood** [comment]
@onebree  Done! Thanks for the ping. c237bdc31b2ca678d66bff210be06f37c407d220
